name: Advanced CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ======================
    # BUILD STAGE
    # ======================
    - name: Build application
      run: |
        echo "Building project..."
        mkdir build
        cp app.txt build/
        echo "build completed"

    # ======================
    # TEST STAGE
    # ======================
    - name: Run tests
      run: |
        echo "Running tests..."
        test -f build/app.txt
        echo "tests passed"

    # ======================
    # START FLoci
    # ======================
    - name: Start Floci (S3 emulator)
      run: |
        docker run -d --name floci -p 4566:4566 floci/floci:latest
        sleep 20

    # ======================
    # INSTALL AWS CLI
    # ======================
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli
        aws --version

    # ======================
    # DEPLOY STAGE
    # ======================
    - name: Create S3 bucket
      run: |
        aws --endpoint-url=http://localhost:4566 s3 mb s3://demo-bucket

    - name: Upload artifact
      run: |
        aws --endpoint-url=http://localhost:4566 s3 cp build/app.txt s3://demo-bucket/

    - name: Verify deployment
      run: |
        aws --endpoint-url=http://localhost:4566 s3 ls s3://demo-bucket